/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hinlogesystem;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Khenyshi
 */
public class GradesForm extends javax.swing.JFrame {

    Grades grades = new Grades();
    static String username;
    static String teachId;
    static String subjid;
    static String eid;
    /**
     * Creates new form GradesForm
     */
    public GradesForm(String username) {
        initComponents();
        
        this.username = username;
        this.teachId = username.substring(0, 4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        subjectTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gradesSubjectTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        studNameInput = new javax.swing.JTextField();
        studIdInput = new javax.swing.JTextField();
        prelimInput = new javax.swing.JComboBox<>();
        midtermInput = new javax.swing.JComboBox<>();
        prefinalInput = new javax.swing.JComboBox<>();
        finalInput = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        gradesTable = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        databaseLabel = new javax.swing.JLabel();

        subjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Subject ID", "Units", "Code", "Description", "Schedule"
            }
        ));
        subjectTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subjectTable);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Teachers Class List/Grades Encoding Form:");

        gradesSubjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Subject ID", "Units", "Code", "Description", "Schedule", "Students"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradesSubjectTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradesSubjectTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(gradesSubjectTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Stud Id");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Stud Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Prelim");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Midterm");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Prefinal");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Final");

        studNameInput.setEditable(false);
        studNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studNameInputActionPerformed(evt);
            }
        });

        studIdInput.setEditable(false);
        studIdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studIdInputActionPerformed(evt);
            }
        });

        prelimInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        prelimInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prelimInputActionPerformed(evt);
            }
        });

        midtermInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        midtermInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midtermInputActionPerformed(evt);
            }
        });

        prefinalInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        prefinalInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefinalInputActionPerformed(evt);
            }
        });

        finalInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        finalInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalInputActionPerformed(evt);
            }
        });

        gradesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Prelim", "Midterm", "Pre Final", "Final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradesTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(gradesTable);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        databaseLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        databaseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        databaseLabel.setText("Database");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel3)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel4)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel5)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel6)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(studNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(prelimInput, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(midtermInput, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(prefinalInput, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(finalInput, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(saveButton)))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(databaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(249, 249, 249))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(databaseLabel)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prelimInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midtermInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prefinalInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjectTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectTableMouseClicked

    }//GEN-LAST:event_subjectTableMouseClicked

    private void studNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studNameInputActionPerformed

    private void studIdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studIdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studIdInputActionPerformed

    private void prelimInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prelimInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prelimInputActionPerformed

    private void midtermInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midtermInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midtermInputActionPerformed

    private void prefinalInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefinalInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prefinalInputActionPerformed

    private void finalInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalInputActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showSubjectList();
        
        prelimInput.addItem(""); 
        midtermInput.addItem(""); 
        prefinalInput.addItem(""); 
        finalInput.addItem(""); 
        
        prelimInput.setSelectedItem(""); 
        midtermInput.setSelectedItem(""); 
        prefinalInput.setSelectedItem(""); 
        finalInput.setSelectedItem(""); 
        
        HinlogESystem system = new HinlogESystem();
        databaseLabel.setText(system.db);
    }//GEN-LAST:event_formWindowOpened

    private void gradesSubjectTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradesSubjectTableMouseClicked
        int row = gradesSubjectTable.getSelectedRow();
        
        subjid = gradesSubjectTable.getValueAt(row, 0).toString();
        grades.subjid = subjid;
        showClassList(subjid);
    }//GEN-LAST:event_gradesSubjectTableMouseClicked

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String prelimGrade = (String) prelimInput.getSelectedItem();
        String midtermGrade = (String) midtermInput.getSelectedItem();
        String prefinalGrade = (String) prefinalInput.getSelectedItem();
        String finalGrade = (String) finalInput.getSelectedItem();

        HinlogESystem system = new HinlogESystem();

        try {
            // check if the grade record already exists for this eid
            String checkQuery = "SELECT COUNT(*) FROM Grades WHERE eid = '" + eid + "'";
            ResultSet rs = system.st.executeQuery(checkQuery);
            rs.next();
            int count = rs.getInt(1);

            if (count > 0) {
                grades.updateRecord(prelimGrade, midtermGrade, prefinalGrade, finalGrade, eid);
            } else {
                grades.saveRecord(prelimGrade, midtermGrade, prefinalGrade, finalGrade, eid);
            }
        } catch (Exception ex) {
            System.out.println("Failed to Save/Update: " + ex);
        }
        showClassList(subjid);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void gradesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradesTableMouseClicked
         int row = gradesTable.getSelectedRow(); // Get clicked row index
        
        // Get values from the table
        String studID = gradesTable.getValueAt(row, 0).toString();
        String studName = gradesTable.getValueAt(row, 1).toString();
        String prelimText = gradesTable.getValueAt(row, 2).toString();
        String midtermText = gradesTable.getValueAt(row, 3).toString();
        String prefinalText = gradesTable.getValueAt(row, 4).toString();
        String finalText = gradesTable.getValueAt(row, 5).toString();
        
        studIdInput.setText(studID);
        studNameInput.setText(studName);
        prelimInput.setSelectedItem(prelimText);
        midtermInput.setSelectedItem(midtermText);
        prefinalInput.setSelectedItem(prefinalText);
        finalInput.setSelectedItem(finalText);

        HinlogESystem system = new HinlogESystem();

        try {
            String query = String.format(
                "SELECT eID FROM Enroll WHERE studID = %s AND subjID = %s",
                studID, subjid
            );
            ResultSet rs = system.st.executeQuery(query);
            if (rs.next()) {
                eid = rs.getString("eID"); // Save it for later use
            }
            rs.close();
        } catch (Exception e) {
            System.out.println("Failed to get eID: " + e);
        }     
    }//GEN-LAST:event_gradesTableMouseClicked

    private void showSubjectList(){      
        DefaultTableModel tblmodel = (DefaultTableModel) gradesSubjectTable.getModel();
        tblmodel.setRowCount(0);
        HinlogESystem system = new HinlogESystem();
        
        try{         
            String query = "SELECT * FROM subjects WHERE subId IN (SELECT subid FROM Assign WHERE tid =" + teachId + ");";    
            system.rs = system.st.executeQuery(query);
            while (system.rs.next())
            {      
                String id = system.rs.getString("subId");
                String units = system.rs.getString("subUnits");
                String code = system.rs.getString("subCode");
                String desc = system.rs.getString("subDescription");
                String sched = system.rs.getString("subSchedule");
                
                String count = "0";
                
                try (Statement st2 = system.con.createStatement();
                     ResultSet result = st2.executeQuery("SELECT COUNT(*) AS count FROM Enroll WHERE subjid = " + id)) {
                    if (result.next()) {
                        count = result.getString("count");
                    }
                }

                String[] item = {id, units, code, desc, sched, count};
                tblmodel.addRow(item);
            }
        }catch(Exception ex){
            System.out.println("Failed to show subjects record" + ex);
            tblmodel.setRowCount(0);
        }
        
    }
    
    private void showClassList(String subjID) {
        DefaultTableModel tblmodel = (DefaultTableModel) gradesTable.getModel();
        tblmodel.setRowCount(0);

        HinlogESystem system = new HinlogESystem();

        try {
            String query = String.format(
                "SELECT s.studID, s.studName, g.Prelim, g.Midterm, g.Prefinal, g.Final " +
                "FROM Enroll e " +
                "JOIN students s ON e.studID = s.studID " +
                "LEFT JOIN Grades g ON e.eID = g.eID " +
                "WHERE e.subjID = %s", subjID
            );
            ResultSet rs = system.st.executeQuery(query);

            while (rs.next()) {
                String studID = rs.getString("studID");
                String studName = rs.getString("studName");
                String prelim = rs.getString("Prelim");
                String midterm = rs.getString("Midterm");
                String prefinal = rs.getString("Prefinal");
                String fin = rs.getString("Final");

                // Handle NULL values (in case grades not entered yet)
                if (prelim == null) prelim = "";
                if (midterm == null) midterm = "";
                if (prefinal == null) prefinal = "";
                if (fin == null) fin = "";

                String[] info = {studID, studName, prelim, midterm, prefinal, fin};
                tblmodel.addRow(info);
            }
            rs.close();
        } catch (Exception exe) {
            System.out.println("failed to get class list: " + exe);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradesForm(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel databaseLabel;
    private javax.swing.JComboBox<String> finalInput;
    private javax.swing.JTable gradesSubjectTable;
    private javax.swing.JTable gradesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> midtermInput;
    private javax.swing.JComboBox<String> prefinalInput;
    private javax.swing.JComboBox<String> prelimInput;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField studIdInput;
    private javax.swing.JTextField studNameInput;
    private javax.swing.JTable subjectTable;
    // End of variables declaration//GEN-END:variables
}
